FROM adminer:4.8.0

ENV ADMINER_DEFAULT_DB_DRIVER=pgsql
ENV ADMINER_DEFAULT_SERVER=postgres
ENV ADMINER_DEFAULT_USER=web
ENV ADMINER_DESIGN=rmsoft

COPY ./login-servers.php /var/www/html/plugins-enabled/login-servers.php